remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "Andrew Cerqui - Data Scientist"
subtitle: "Turning data into actionable insights"
description: "Data Science Portfolio showcasing analytical projects and skills"
url: "https://ajcerqui.github.io"  
repository: "ajcerqui/ajcerqui.github.io"  

# Author info
author:
  name: "Andrew Cerqui"
  avatar: "/assets/images/bio-photo.jpg" # Add your photo here later
  bio: "Data Science graduate student with experience in statistical analysis, business intelligence, and data visualization"
  location: "Salem, OR"
  email: "andrewjcerqui@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrew-cerqui-3a4b5c"

# Navigation
navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections for projects
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
